---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: datawire/telepresence-k8s:0.42
          ports:
            - containerPort: 8080
#          env:
#            - name: PGSQL_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: helloworld
#                  key: pg_username
#            - name: PGSQL_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: helloworld
#                  key: pg_password
#            - name: PGSQL_URL
#              valueFrom:
#                secretKeyRef:
#                  name: helloworld
#                  key: pg_url
